import { mkdir, cp } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { examples } from '../src/examples';
import { specPage } from './spec-page';
import { prepareOutput, run } from './artifacts';
import { dependencyNotices } from './notices';
import { publishedDocs, siteHeaders } from './site-config';

const release = process.argv.includes('--release');
const out = release ? await prepareOutput('site') : 'site';
const files = {
  spec: 'SPEC.md',
  components: 'docs/semantics.md',
  future: 'site/future.md',
  implementation: 'guidelines/implementation.md',
};
const documents: Record<string, string> = {};
for (const [key, path] of Object.entries(files)) documents[key] = await Bun.file(path).text();
const sections = specPage(documents.spec, documents.components);
const shown = sections.flatMap((section) => section.examples);
if (
  new Set(shown).size !== examples.length ||
  shown.length !== examples.length ||
  shown.some((id) => !examples.some((example) => example.id === id))
)
  throw new Error('Every example must appear exactly once');
await Bun.write(
  'src/content.generated.ts',
  '// Generated by scripts/build.ts.\nexport const documents = ' +
    JSON.stringify(documents) +
    ';\nexport const sections = ' +
    JSON.stringify(sections) +
    ';\n',
);
const result = await Bun.build({
  entrypoints: ['src/app.ts'],
  outdir: out,
  target: 'browser',
  format: 'esm',
  splitting: true,
  naming: {
    entry: '[name].[ext]',
    chunk: 'chunks/[name]-[hash].[ext]',
    asset: 'assets/[name]-[hash].[ext]',
  },
  minify: true,
});
if (!result.success) throw new AggregateError(result.logs, 'Site build failed');
await mkdir(join(out, 'katex'), { recursive: true });
await cp('node_modules/katex/dist/katex.min.css', join(out, 'katex/katex.min.css'));
await cp('node_modules/katex/dist/fonts', join(out, 'katex/fonts'), { recursive: true });
await cp('src/styles.css', join(out, 'afm.css'));
if (release)
  for (const name of ['index.html', 'style.css', 'media'])
    await cp(join('site', name), join(out, name), { recursive: true });
await Bun.write(
  'EXAMPLES.md',
  '# AFM examples\n\nGenerated from src/examples.ts. Live examples use the reference TypeScript renderer.\n\n' +
    examples
      .map(
        (example) =>
          '## ' +
          example.title +
          '\n\n' +
          example.description +
          '\n\n````markdown\n' +
          example.source +
          '\n````\n',
      )
      .join('\n'),
);
for (const source of publishedDocs) {
  const target = join(out, 'spec', source);
  await mkdir(dirname(target), { recursive: true });
  await cp(source, target);
}
await Bun.write(join(out, 'THIRD-PARTY-NOTICES.md'), await dependencyNotices());
await cp('LICENSE', join(out, 'LICENSE'));
await Bun.write(
  join(out, '_headers'),
  '/*\n' +
    Object.entries(siteHeaders)
      .map(([key, value]) => `  ${key}: ${value}`)
      .join('\n') +
    '\n',
);
await Bun.write(
  join(out, '404.html'),
  '<!doctype html><html lang="en"><meta charset="utf-8"><title>Not found — AFM</title><p>Page not found.</p></html>\n',
);
if (release)
  await run(['tar', '-czf', 'dist/afm-site.tar.gz', '-C', out, '--exclude=.afm-build', '.']);
console.log(`Built ${out}${release ? ' and dist/afm-site.tar.gz' : ''}.`);
